language:
  - python3

install:
  - sudo apt install python3-pip
  - sudo python3 -m pip install pytest
  - sudo python3 -m pip install python-coveralls
  - sudo python3 -m pip install pytest-cov

before_scrip:
  - py.test tests/ --cov=azazel

script:
  - pytest

after_success:
  - coveralls
