language:
  - python

python:
  - "3.6"

install:
  - sudo apt-get install python3-pip
  - sudo pip install pytest
  - sudo pip install python-coveralls
  - sudo pip install pytest-cov
  - sudo pip install --upgrade setuptools
script:
  - python --version
  - py.test tests/ --cov=azazel

after_success:
  - coveralls
