language:
  - python

python:
  - "3.6"

install:
  - sudo apt-get install python3-pip
  - sudo python3 -m pip install pytest
  - sudo python3 -m pip install python-coveralls
  - sudo python3 -m pip install pytest-cov

script:
  - py.test tests/ --cov=azazel

after_success:
  - coveralls
